name: Publish documentation

on:
  push:
    branches:
      - master

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build documentation
      run: cargo doc --all --no-deps
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: docs
        publish_dir: ./target/doc
        force_orphan: true